# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "passifier"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ari Russo"]
  s.date = "2013-06-11"
  s.description = "Generate Apple Passbook passes in Ruby"
  s.email = "ari.russo@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.md",
    "README.md",
    "Rakefile",
    "examples/assets/background.png",
    "examples/assets/background@2x.png",
    "examples/assets/icon.png",
    "examples/assets/icon@2x.png",
    "examples/assets/logo.png",
    "examples/assets/logo@2x.png",
    "examples/assets/thumbnail.png",
    "examples/assets/thumbnail@2x.png",
    "examples/simple.rb",
    "lib/passifier.rb",
    "lib/passifier/archive.rb",
    "lib/passifier/manifest.rb",
    "lib/passifier/manifest_signature.rb",
    "lib/passifier/pass.rb",
    "lib/passifier/signing.rb",
    "lib/passifier/spec.rb",
    "lib/passifier/static_file.rb",
    "lib/passifier/storage.rb",
    "lib/passifier/url_source.rb",
    "test/assets/background.png",
    "test/assets/background@2x.png",
    "test/assets/icon.png",
    "test/assets/icon@2x.png",
    "test/assets/logo.png",
    "test/assets/logo@2x.png",
    "test/assets/thumbnail.png",
    "test/assets/thumbnail@2x.png",
    "test/helper.rb",
    "test/passifier/test_archive.rb",
    "test/passifier/test_manifest.rb",
    "test/passifier/test_manifest_signature.rb",
    "test/passifier/test_pass.rb",
    "test/passifier/test_signing.rb",
    "test/passifier/test_spec.rb",
    "test/passifier/test_static_file.rb",
    "test/passifier/test_storage.rb",
    "test/passifier/test_url_source.rb",
    "test/test_passifier.rb"
  ]
  s.homepage = "http://github.com/paperlesspost/passifier"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Generate Apple Passbook passes in Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

